name: Preview

on:
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }} @ pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/call-ci.yml
    with:
      environment: Preview
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCESS_CLIENT_ID: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_ID }}
      CLOUDFLARE_ACCESS_CLIENT_SECRET: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET }}
